export const endpoints = {
  user: {
    list: '/api/users',
    create: '/api/users',
    detail: (id) => `/api/users/${id}`,
    update: (id) => `/api/users/${id}`,
    delete: (id) => `/api/users/${id}`,
    changePassword: (id) => `/api/users/${id}/change-password`,
    activityLog: (id) => `/api/users/${id}/user-history`,
    bulkUpload: '/api/users/bulk-upload',
    csvExport: '/api/users/csv-export',
    excelExport: '/api/users/excel-export',
    branches: '/api/users/branches',
    assignedBranch: '/api/users/assigned-branch',
  },
  rolePermission: {
    list: '/api/role-permissions',
    create: '/api/role-permissions',
    update: (id) => `/api/role-permissions/${id}`,
    delete: (id) => `/api/role-permissions/${id}`,
    getMenus: '/api/role-permissions/menus',
  },
  plUpload: {
    list: '/api/pl-upload',
    status: '/api/pl-upload/status',
    csvExport: '/api/pl-upload/csv-export',
    excelExport: '/api/pl-upload/excel-export',
    plLogs: '/api/pl-upload/pl-logs',
    plExceptions: '/api/pl-upload/pl-exceptions',
    delete: (id) => `/api/pl-upload/${id}`,
    plCreate: '/api/pl-upload/create',
    reUpload: '/api/pl-upload/re-upload',
  },
  plMasterfile: {
    list: '/api/pl-masterfile',
    status: '/api/pl-masterfile/status',
    csvExport: '/api/pl-masterfile/csv-export',
    excelExport: '/api/pl-masterfile/excel-export',
  },
  branch: {
    list: '/api/branch',
    csvExport: '/api/branch/csv-export',
    excelExport: '/api/branch/excel-export',
  },
  item: {
    list: '/api/item/item-fetch',
    csvExport: '/api/item/csv-export',
    excelExport: '/api/item/excel-export',
    rowsUpdate: '/api/item/update-rows',
  },
  initialPlReceiving: {
    list: '/api/initial-pl-receiving',
    hasZero: '/api/initial-pl-receiving/has-zero',
    status: '/api/initial-pl-receiving/status',
    csvExport: '/api/initial-pl-receiving/csv-export',
    excelExport: '/api/initial-pl-receiving/excel-export',
    fileSI: '/api/initial-pl-receiving/filename-si_number',
    rowsUpdate: '/api/initial-pl-receiving/rows-update',
    toConfirm: '/api/initial-pl-receiving/to-confirm',
    plsFiles: (branch_id) => `/api/initial-pl-receiving/branch/${branch_id}/filenames`,
  },
};
